In [1]:
import numpy as np
import numpy.random as random

In [2]:
def basis(n_basis):
    dic = dict({})
    
    for i in range(1, n_basis +1):
        _ = np.zeros(n_basis)
        _[i-1] = 1
        dic[f"e{i}"] = _
    return dic

class Dice():
    
    def __init__(self, prob):
        self.prob = np.array(prob)

In [3]:
def create_prob_state(n):
    probs = random.randint(1, 10000\
                           , size = n)
    probs = probs / probs.sum()
    return probs

In [4]:
create_prob_state(10)

array([0.08465253, 0.13209462, 0.05238602, 0.07397888, 0.06400917,
       0.11546206, 0.1518376 , 0.10932307, 0.1333879 , 0.08286813])

In [12]:
x = basis(2)


array([1., 0.])

In [13]:
y = np.tensordot(x['e1'], x['e2'], axes = 0)
for i in [2, 2]:
    y = np.tensordot(x[f'e{i}'], y, axes = 0)

In [14]:
y

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 1.],
         [0., 0.]]]])