In [1]:
import numpy as np

In [31]:
def prob_oper(n):
    M = np.zeros(shape = [n, n])
    for i in range(n):
        for j in range(n):
            M[i, j] = np.random.randint(1, 100)
    #print(M)
    for i in range(n):
        M[:, i] = M[:, i] / (M[:, i]).sum()
    return np.matrix(M)

In [32]:
x = prob_oper(3)

In [37]:
x[:, 1]

matrix([[0.40336134],
        [0.26470588],
        [0.33193277]])

In [36]:
x = 

matrix([[0.32421875, 0.40336134, 0.3440367 ],
        [0.328125  , 0.26470588, 0.38073394],
        [0.34765625, 0.33193277, 0.27522936]])

In [38]:
I = np.matrix("0.999 0.001;0.001 0.999")

In [50]:
v = np.array([0.2, 0.8])
w = np.array([0.6, 0.4])

In [51]:
np.tensordot(v, w, axes = 0)

array([[0.12, 0.08],
       [0.48, 0.32]])